name: KBuddy-server Jenkins

on:
  push:
    branches:
      - dev
    tags:
      - "v*.*.*"  # 버전 태그를 달아 배포할 때 사용할 태그 필드
#  pull_request:
#    types:
#      - closed
jobs:
#  build-server-image:
#    # if: github.event.pull_request.merged == true
#    name: Build on ARM
#    runs-on: ubuntu-latest
#    env:
#      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
#      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
#      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
#      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
#      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#        with:
#          platforms: arm64
#
#      - name: Create .env file
#        run: |
#          cat <<EOF > .env
#          echo "DB_USER=${{ secrets.DB_USER }}" > .env
#          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
#          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env
#          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
#          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
#          echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env
#          echo "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}" >> .env
#          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env
#          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> .env
#          EOF
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Get or create an OCIR Repository
#        uses: oracle-actions/get-ocir-repository@v1.3.0
#        id: get-ocir-repository
#        with:
#          name: kbuddy-server
#          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
#        continue-on-error: false
#
#      - name: Log into OCIR
#        uses: oracle-actions/login-ocir@v1.3.0
#        id: login-ocir
#        with:
#          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: |
#            ${{ steps.get-ocir-repository.outputs.repo_path }}
#          flavor: |
#            latest=true
#          tags: |
#            type=sha
#
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          platforms: linux/arm64
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

  post-discord:
    name: Post CI result to Discord
    runs-on: ubuntu-latest
    needs: build-server-image
    steps:
      - name: Post to Discord channel
        if: always()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          title: 'KBuddy Server Github Action Build Result'
          content: |
            **KBuddy Server Jenkins Build Result**
            - **Build Status**: ${{ needs.build-server-image.result }}
            - **Build URL**: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
            - **Build Duration**: ${{ job.status == 'success' && job.steps[0].outputs.duration || 'N/A' }} seconds
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'

  trigger-jenkins:
    # if: github.event.pull_request.merged == true
    name: Jenkins-action
    runs-on: ubuntu-latest
#    needs: build-server-image
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "k-buddy"

